image: registry.gitlab.com/elypia/elypia-emotes/imagemagick:7.0.8.44-r0

cache:
  key: $CI_PIPELINE_ID

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: 
    - sh scripts/test.sh

build:
  stage: build
  script:
    - sh scripts/build.sh
  cache:
    policy: push
    paths:
      - output/
  artifacts:
    paths:
      - output/

pages:
  stage: deploy
  script:
    - sh scripts/pages.sh
  cache:
    policy: pull
    paths:
      - output/
  artifacts:
    paths:
      - public/
