image: registry.gitlab.com/elypia/elypia-emotes:experimental

cache:
  key: $CI_PIPELINE_ID

# Prepare coverers testing and building, this is to push on speed as they can
# be done in parralel. This should make succesful builds faster, however
# make builds that fail take potentially longer to fail.
stages:
  - test
  - build
  - deploy

test:
  image: bash:5.0.7
  stage: test
  script: 
    - bash scripts/test.sh

build:
  stage: build
  script:
    - bash scripts/build.sh
  cache:
    policy: push
    paths:
      - output/
      - public/
  artifacts:
    paths:
      - output/
      - LICENSE

pages:
  image: alpine:3.10.1
  stage: deploy
  script:
    - echo Deploying
  cache:
    policy: pull
    paths:
      - output/
      - public/
  artifacts:
    paths:
      - public/
