image: elypia/imagecaster:0.4.0-q8

stages: 
  - test
  - build
  - deploy

cache:
  paths:
    - .imagecaster/
    - build/

test:
  stage: test
  script: 
    - imagecaster check
  cache: {}

build:
  stage: build
  script:
    - imagecaster build
    - imagecaster montage
    - imagecaster archive
  artifacts:
    paths:
      - build/montages/*
      - build/archives/*
