image: elypia/imagecaster:0.2.1-q8

stages: 
  - test
  - build
  - deploy

cache:
  policy: pull-push
  paths:
    - .imagecaster/
    - build/

test:
  stage: test
  script: 
    - imagecaster check
  cache: {}

build:
  stage: build
  script:
    - imagecaster build
    - imagecaster montage
    - imagecaster archive

pages:
  stage: deploy
  only: 
    - master
  script:
    - mkdir public
    - mv build/montages/* public/
    - mv build/archives/* public/
  artifacts:
    paths:
      - public/
