image: elypia/imagecaster:1.0.0

cache:
  paths:
    - .imagecaster/
    - build/

test:
  script: 
    - imagecaster check

build:
  script:
    - imagecaster build

pages:
  stage: deploy
  only: 
    - master
  script:
    - imagecaster montage
  artifacts:
    paths:
      - public/
