image: registry.gitlab.com/elypia/elypia-emotes/imagemagick:7.0.8.44-r0

test:
  stage: test
  script:
    - sh scripts/test.sh

pages:
  stage: deploy
  script:
    - sh scripts/build.sh
  artifacts:
    paths:
      - output
      - public
