image: elypia/imagecaster:0.1.0

cache:
  policy: pull-push
  paths:
    - .imagecaster/
    - build/

test:
  script: 
    - imagecaster check
  cache: {}

build:
  script:
    - imagecaster build
    - imagecaster montage

pages:
  stage: deploy
  only: 
    - master
  script:
    - mkdir -p public
    - mv build/montages/ public/
  artifacts:
    paths:
      - public/
