image: registry.gitlab.com/elypia/elypia-emotes:latest

cache:
  key: $CI_PIPELINE_ID

stages:
  - test
  - build
  - deploy

test:
  image: bash:5.0.7
  stage: test
  script: 
    - bash scripts/test.sh

build:
  stage: build
  script:
    - bash scripts/build.sh
  cache:
    policy: push
    paths:
      - public/

pages:
  image: alpine:3.10.1
  stage: deploy
  script:
    - echo Deploying
  cache:
    policy: pull
    paths:
      - public/
  artifacts:
    paths:
      - public/
