image: elypia/imagecaster:1.0.0

cache:
  paths:
    - .imagecaster/
    - build/

test:
  stage: test
  script: 
    - imagecaster test

build:
  stage: build
  script:
    - imagecaster build

pages:
  stage: deploy
  script:
    - imagecaster montage
  artifacts:
    paths:
      - public/
